### ISSUE TITLE
app.CRITICAL: Signature Verification Failed

### ISSUE THREAD

**Issue by sanjinhadzic** [tiamo/phpas2#35]
Hello,

I get 

[2022-01-28 15:24:14] app.CRITICAL: Signature Verification Failed [] []

My installation works with previous partner.

I received the certificate file in binary .cer format and then converted it using openssl to .crt so i can use it with my code ( because my previous partner had that file format and it works).

Any idea how can i fix this ?

Thank you.

**Comment by robsonala** [comment]
This error is happening because the certificate is not matching the one necessary to validate the message.
The possible problems:
- You are using the incorrect certificate
- You have extract the public key wrongly

https://superuser.com/questions/1660060/extract-rsa-public-key-from-public-certificate 

thanks,
R.

**Comment by robsonala** [comment]
@tiamo You can close this one as it is not an issue
